workflows:
  ios_app_store:
    name: TopRoad • App Store
    max_build_duration: 120

    integrations:
      app_store_connect: "Mattie Navarro"

    environment:
      xcode: 16.0
      vars:
        PROJECT_PATH: "TopRoad.xcodeproj"
        SCHEME: "TopRoad"
        BUNDLE_ID: "com.navattomat.toproad"
        APPLE_ID: "6751043815"
        EXPORT_METHOD: "app-store"
        DEVELOPMENT_TEAM: "B47F5B97FC"   # ← 10-символьный Team ID (не имя!)

    scripts:
      - name: Tools info
        script: |
          xcodebuild -version
          swift --version
          echo "Team: $DEVELOPMENT_TEAM"

      - name: Increment build number
        script: |
          BUILD_NUMBER=${BUILD_NUMBER_OFFSET:-0}
          BUILD_NUMBER=$((BUILD_NUMBER + $CM_BUILD_ID))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "TopRoad/Info.plist" || true

      - name: Resolve Swift Package Manager
        script: |
          xcodebuild -resolvePackageDependencies -project "$PROJECT_PATH" -scheme "$SCHEME"

      - name: Archive (Release)
        script: |
          set -e
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/TopRoad.xcarchive" \
            clean archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            -allowProvisioningUpdates

      - name: Export .ipa
        script: |
          set -e
          cat > $CM_BUILD_DIR/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TopRoad.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/export" \
            -allowProvisioningUpdates

    artifacts:
      - "$CM_BUILD_DIR/export/*.ipa"
      - "$CM_BUILD_DIR/TopRoad.xcarchive"
      - "$CM_BUILD_DIR/ExportOptions.plist"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
