workflows:
  ios_app_store:
    name: TopRoad • App Store
    max_build_duration: 120

    # используем интеграцию App Store Connect по имени
    integrations:
      app_store_connect: "Mattie Navarro"

    environment:
      xcode: 16.0
      vars:
        PROJECT_PATH: "TopRoad.xcodeproj"
        SCHEME: "TopRoad"
        BUNDLE_ID: "com.navattomat.toproad"
        APPLE_ID: "6751043815"
        EXPORT_METHOD: "app-store"
        DEVELOPMENT_TEAM: "88LASY7459"   # ← подставь свой Team ID (10 символов)
      # кэш SPM
    cache:
      cache_paths:
        - "$HOME/Library/Caches/org.swift.swiftpm"
        - "$HOME/Library/Developer/Xcode/DerivedData"

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Tools info
        script: |
          xcodebuild -version
          swift --version
          echo "Team ID: $DEVELOPMENT_TEAM"
          echo "BundleID: $BUNDLE_ID"

      - name: Resolve Swift Package Manager
        script: |
          xcodebuild -resolvePackageDependencies -project "$PROJECT_PATH" -scheme "$SCHEME"

      # ⬇️ СКАЧИВАЕМ сертификаты/профили из App Store Connect и кладём в keychain
      - name: Fetch signing files (App Store)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --team-id "$DEVELOPMENT_TEAM"
          keychain add-certificates

      # ⬇️ Применяем скачанные профили к текущему Xcode-проекту
      - name: Use fetched provisioning profiles
        script: |
          xcode-project use-profiles

      # ⬇️ Инкремент сборки (по желанию)
      - name: Increment build number
        script: |
          BUILD_NUMBER=${BUILD_NUMBER_OFFSET:-0}
          BUILD_NUMBER=$((BUILD_NUMBER + $CM_BUILD_ID))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "TopRoad/Info.plist" || true
          echo "CFBundleVersion = $BUILD_NUMBER"

      # ⬇️ Архив и экспорт IPA через удобную команду Codemagic (учитывает применённые профили)
      - name: Build IPA (App Store)
        script: |
          xcode-project build-ipa \
            --project "$PROJECT_PATH" \
            --scheme "$SCHEME" \
            --archive-method "$EXPORT_METHOD" \
            --team-id "$DEVELOPMENT_TEAM"

      - name: List artifacts
        script: |
          ls -la build/ios/ipa || true

    artifacts:
      - "build/ios/ipa/*.ipa"
      - "$CM_BUILD_DIR/TopRoad.xcarchive"
      - "$HOME/Library/Logs/DiagnosticReports/*.crash"

    publishing:
      app_store_connect:
        auth: integration        # использует integrations.app_store_connect
        submit_to_testflight: true
        submit_to_app_store: true
      email:
        recipients:
          - "you@example.com"
        notify:
          success: true
          failure: true
