workflows:
  ios_app_store:
    name: TopRoad • App Store
    max_build_duration: 120
    environment:
      xcode: 15.4
      vars:
        PROJECT_PATH: "TopRoad/TopRoad.xcodeproj"   # <-- проверь путь!
        SCHEME: "TopRoad"
        BUNDLE_ID: "com.navattomat.toproad"
        APPLE_ID: "6751043815"
        EXPORT_METHOD: "app-store"
      groups:
        - "Mattie Navarro"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    cache:
      cache_paths:
        - "$HOME/Library/Caches/org.swift.swiftpm"
        - "$HOME/Library/Developer/Xcode/DerivedData"
    scripts:
      - name: Show tools
        script: |
          xcodebuild -version
          swift --version
          echo "Project: $PROJECT_PATH"
          echo "Scheme : $SCHEME"

      - name: Increment build number
        script: |
          BUILD_NUMBER=${BUILD_NUMBER_OFFSET:-0}
          BUILD_NUMBER=$((BUILD_NUMBER + $CM_BUILD_ID))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "TopRoad/Info.plist" || true
          echo "CFBundleVersion set to $BUILD_NUMBER"

      - name: Resolve Swift Package Manager
        script: |
          xcodebuild -resolvePackageDependencies -project "$PROJECT_PATH" -scheme "$SCHEME"

      - name: Archive (Release)
        script: |
          set -e
          xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/TopRoad.xcarchive" \
            clean archive \
            CODE_SIGN_STYLE=Automatic

      - name: Export .ipa
        script: |
          set -e
          cat > $CM_BUILD_DIR/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TopRoad.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/export"

      - name: List artifacts
        script: ls -la "$CM_BUILD_DIR/export" || true

    artifacts:
      - "$CM_BUILD_DIR/export/*.ipa"
      - "$CM_BUILD_DIR/TopRoad.xcarchive"
      - "$CM_BUILD_DIR/ExportOptions.plist"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
      email:
        recipients:
          - "you@example.com"
        notify:
          success: true
          failure: true
